In [1]:
import torch
import numpy as np

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.randint(1,9,(3,4,5)).type(torch.FloatTensor)
a

tensor([[[8., 2., 7., 1., 6.],
         [8., 1., 6., 6., 1.],
         [5., 8., 7., 1., 5.],
         [8., 5., 6., 8., 2.]],

        [[7., 6., 7., 2., 5.],
         [2., 5., 5., 6., 7.],
         [4., 8., 5., 8., 8.],
         [7., 6., 6., 7., 5.]],

        [[7., 5., 2., 4., 7.],
         [2., 3., 5., 7., 5.],
         [4., 2., 5., 1., 3.],
         [6., 1., 8., 7., 6.]]])

In [3]:
# Выведите его форму (shape)
a.shape, a.type()

(torch.Size([3, 4, 5]), 'torch.FloatTensor')

In [4]:
# Приведите его к форме 6 X 10
b = a.reshape((6,10))
b, b.size()

(tensor([[8., 2., 7., 1., 6., 8., 1., 6., 6., 1.],
         [5., 8., 7., 1., 5., 8., 5., 6., 8., 2.],
         [7., 6., 7., 2., 5., 2., 5., 5., 6., 7.],
         [4., 8., 5., 8., 8., 7., 6., 6., 7., 5.],
         [7., 5., 2., 4., 7., 2., 3., 5., 7., 5.],
         [4., 2., 5., 1., 3., 6., 1., 8., 7., 6.]]),
 torch.Size([6, 10]))

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x = torch.FloatTensor([1,4,2,2,1])
y = a * x
y

tensor([[[ 8.,  8., 14.,  2.,  6.],
         [ 8.,  4., 12., 12.,  1.],
         [ 5., 32., 14.,  2.,  5.],
         [ 8., 20., 12., 16.,  2.]],

        [[ 7., 24., 14.,  4.,  5.],
         [ 2., 20., 10., 12.,  7.],
         [ 4., 32., 10., 16.,  8.],
         [ 7., 24., 12., 14.,  5.]],

        [[ 7., 20.,  4.,  8.,  7.],
         [ 2., 12., 10., 14.,  5.],
         [ 4.,  8., 10.,  2.,  3.],
         [ 6.,  4., 16., 14.,  6.]]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
b2 = torch.matmul(b, b.T)
b2, b2.size()

(tensor([[292., 291., 243., 284., 222., 235.],
         [291., 357., 292., 355., 255., 256.],
         [243., 292., 302., 318., 257., 233.],
         [284., 355., 318., 428., 302., 264.],
         [222., 255., 257., 302., 255., 207.],
         [235., 256., 233., 264., 207., 241.]]),
 torch.Size([6, 6]))

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

In [8]:
y = x**3 + z - 75*t

## 3x^2 + 1 - 75

In [9]:
y.backward()

In [10]:
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [11]:
# Создайте единичный тензор размера 5x6
ed = torch.ones((5,6))
ed

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [12]:
# Переведите его в формат numpy
ed.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [23]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте
x = torch.tensor([2.0], requires_grad=True)
w1 = torch.tensor([3.0], requires_grad=True)
y = x**w1 - 2 * x**2 + 5
y.backward()
x.grad, w1.grad

(tensor([4.]), tensor([5.5452]))