### 1. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [28]:
import numpy as np

In [1]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [38]:
mean_a = a.mean(axis =0)
mean_a

array([2. , 8.4])

### 2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [4]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### 3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [24]:
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1])
a_centered_sp

8.0

In [33]:
N = a_centered_sp / (a.shape[0] - 1)
N

2.0

### 4**. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [36]:
np.cov(a.T)[0, 1]

2.0

# Работа с данными Pandas

### 1. Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  [1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], [450, 300, 350, 500, 450, 370, 290].


In [2]:
import pandas as pd

In [3]:
authors = pd.DataFrame({'author_id':[1,2,3], 'author_name':['Turgenev', 'Chehov', 'Ostrovsky']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Turgenev
1          2      Chehov
2          3   Ostrovsky

In [4]:
books = pd.DataFrame({'author_id':[1,1,1,2,2,3,3], 'book_title':['Faters and Sons', 'Rudin', 'Nobiliary nest', 'Thick and thin', 'The Lady with the dog', 'Thunderstorm', 'Talent and fans'], 'price':[450,300,350,500,450,370,290]}, columns=['author_id','book_title','price'])
books

author_id             book_title  price
0          1        Faters and Sons    450
1          1                  Rudin    300
2          1         Nobiliary nest    350
3          2         Thick and thin    500
4          2  The Lady with the dog    450
5          3           Thunderstorm    370
6          3        Talent and fans    290

### 2. Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [5]:
authors_price = pd.merge(authors, books, on='author_id', how='outer')
authors_price

author_id author_name             book_title  price
0          1    Turgenev        Faters and Sons    450
1          1    Turgenev                  Rudin    300
2          1    Turgenev         Nobiliary nest    350
3          2      Chehov         Thick and thin    500
4          2      Chehov  The Lady with the dog    450
5          3   Ostrovsky           Thunderstorm    370
6          3   Ostrovsky        Talent and fans    290

In [6]:
authors_price.groupby('author_name').agg({'price': 'max'})

price
author_name       
Chehov         500
Ostrovsky      370
Turgenev       450

### 3. Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [22]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name             book_title  price
3          2      Chehov         Thick and thin    500
0          1    Turgenev        Faters and Sons    450
4          2      Chehov  The Lady with the dog    450
5          3   Ostrovsky           Thunderstorm    370
2          1    Turgenev         Nobiliary nest    350

### 4. Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [24]:
author_group = authors_price.groupby('author_name')
author_stat = pd.DataFrame({'min_price':author_group['price'].min(),'max_price':author_group['price'].max(),'mean_price':author_group['price'].mean()})
author_stat

min_price  max_price  mean_price
author_name                                  
Chehov             450        500  475.000000
Ostrovsky          290        370  330.000000
Turgenev           300        450  366.666667

### 5**. Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [30]:
authors_price['cover'] = ['solid','soft','soft','solid','solid','soft','soft']
authors_price

author_id author_name             book_title  price  cover
0          1    Turgenev        Faters and Sons    450  solid
1          1    Turgenev                  Rudin    300   soft
2          1    Turgenev         Nobiliary nest    350   soft
3          2      Chehov         Thick and thin    500  solid
4          2      Chehov  The Lady with the dog    450  solid
5          3   Ostrovsky           Thunderstorm    370   soft
6          3   Ostrovsky        Talent and fans    290   soft

In [31]:
?pd.pivot_table

In [38]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name', 'book_title'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover                              soft  solid
author_name book_title                        
Chehov      The Lady with the dog     0    450
            Thick and thin            0    500
Ostrovsky   Talent and fans         290      0
            Thunderstorm            370      0
Turgenev    Faters and Sons           0    450
            Nobiliary nest          350      0
            Rudin                   300      0

In [52]:
book_info.to_pickle('book_info.pkl')

In [53]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover                              soft  solid
author_name book_title                        
Chehov      The Lady with the dog     0    450
            Thick and thin            0    500
Ostrovsky   Talent and fans         290      0
            Thunderstorm            370      0
Turgenev    Faters and Sons           0    450
            Nobiliary nest          350      0
            Rudin                   300      0

In [56]:
book_info.equals(book_info2)

True